import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

import Portfolio from "./Portfolio";
import Experience from "./Experience";
import AboutMe from "./AboutMe";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.navbar}></div>
        <nav className={styles.nav}>
          <Image
            src="/vercel.svg"
            alt="Vercel Logo"
            width={72}
            height={16}
          ></Image>{" "}
          <h2 className={styles.headerText}>code.allan</h2>
          <input
            id="menu_toggle"
            className={styles.menu_toggle}
            type="checkbox"
          />
          <label className={styles.menu_button_container} htmlFor="menu_toggle">
            <div className={styles.menu_button}></div>
          </label>
          <ul className={styles.menu}>
            <li>
              <Link href="#Portfolio">
                <a className={styles.nav_link}>Portfolio</a>
              </Link>
            </li>
            <li>
              <Link href="#Experience">
                <a className={styles.nav_link}>Experience</a>
              </Link>
            </li>
            <li>
              <Link href="#AboutMe">
                <a className={styles.nav_link}>About Me</a>
              </Link>
            </li>
          </ul>
        </nav>
        <section className={styles.section_dynamic}>
          <section className={styles.feature_news}>
            <div></div>
            <div></div>
            <div></div>
            <h1 className={styles.title}>
              Finding solutions <br /> within code.
            </h1>
          </section>
          <Portfolio />
          <Experience />
          <AboutMe />
        </section>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
