import type {
  NextPage,
  GetServerSideProps,
  InferGetServerSidePropsType,
} from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect } from "react";
import CarouselHorizontal from "./CarouselHorizontal";

import styles from "../styles/Home.module.css";

const Home: NextPage = ({
  news,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  // console.log(news);
  useEffect(() => {
    document.addEventListener("DOMContentLoaded", function () {
      //dom is fully loaded, but maybe waiting on images & css files
      if (window) {
        window.$ = window.jQuery = require("jquery");
      }
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navbar}></div>
      <nav className={styles.nav}>
        <Image
          src="/vercel.svg"
          alt="Vercel Logo"
          width={72}
          height={16}
        ></Image>{" "}
        <h2 className={styles.headerText}>code.allan</h2>
        <input
          id="menu_toggle"
          className={styles.menu_toggle}
          type="checkbox"
        />
        <label className={styles.menu_button_container} htmlFor="menu_toggle">
          <div className={styles.menu_button}></div>
        </label>
        <ul className={styles.menu}>
          <li>
            <Link href="./Portfolio">
              <a className={styles.nav_link}>Portfolio</a>
            </Link>
          </li>
          <li>
            <Link href="./Experience">
              <a className={styles.nav_link}>Experience</a>
            </Link>
          </li>
          <li>
            <Link href="./AboutMe">
              <a className={styles.nav_link}>About Me</a>
            </Link>
          </li>
        </ul>
      </nav>
      <main className={styles.main}>
        <section className={styles.section_dynamic}>
          <section className={styles.feature_news}>
            {/* <div className={styles.section_carousel}> */}
            <CarouselHorizontal data={news} row={1} />
            <CarouselHorizontal data={news} row={2} rtl={true} />
            <CarouselHorizontal data={news} row={3} />

            <h1 className={styles.title}>
              Finding solutions <br /> within code.
            </h1>
          </section>
        </section>
      </main>
      <footer className={styles.footer}>
        <span>code.allan</span>
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const options = {
    method: "GET",
    headers: {
      "X-Api-Key": `${process.env.NEWSAPI_KEY}`,
    },
  };

  const res = await fetch(
    "https://newsapi.org/v2/everything?q=software&sortBy=popularity&pageSize=30&excludeDomains=lifehacker.com&page=1",
    options
  );
  const data = await res.json();

  let news: object[] = [];

  data.articles.map((item: any) => {
    let newsObj: any = new Object({
      title: item.title,
      url: item.url,
      imageUrl: item.urlToImage,
    });
    news.push(newsObj);
  });

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      news,
    },
  };
};

export default Home;
